'use strict';

const fs = require('fs');
const path = require('path');

/**
 * The only keys the setup wizard is allowed to write. Matches the wizard-writable
 * set in PLAN.md §5.3 behavior step 2 and docs/spec/server/routes/setup.md.
 */
const WIZARD_WRITABLE_KEYS = Object.freeze([
  'WEA_STORAGE_BACKEND',
  'WEA_PG_HOST',
  'WEA_PG_PORT',
  'WEA_PG_DATABASE',
  'WEA_PG_USER',
  'WEA_PG_PASSWORD',
  'WEA_PG_SSL',
  'WEA_PG_MAX',
  'WEA_FILE_STORAGE',
  'S3_BUCKET',
  'AWS_REGION',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'S3_ENDPOINT',
  'WEBDAV_URL',
  'WEBDAV_USERNAME',
  'WEBDAV_PASSWORD',
  'WEBDAV_AUTH_TYPE',
  'JWT_SECRET',
  'JWT_EXPIRES_IN',
  'PORT',
  'CORS_ORIGINS',
  'ADMIN_DEFAULT_PASSWORD',
  'EMAIL_HOST',
  'EMAIL_PORT',
  'EMAIL_USER',
  'EMAIL_PASSWORD',
  'EMAIL_SECURE',
  'EMAIL_FROM_NAME',
  // T0 master key: auto-generated by the wizard when absent (keep-existing
  // otherwise) so DB secrets encrypted with it stay decryptable after restart.
  'encrypt_secret_key',
]);

const ALLOWED_KEY_SET = new Set(WIZARD_WRITABLE_KEYS);

const ASSIGNMENT_RE = /^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*=(.*)$/;

function validateEntries(entries) {
  if (entries === null || typeof entries !== 'object' || Array.isArray(entries)) {
    throw new TypeError('entries must be a flat object of allowlisted keys');
  }
  for (const [key, value] of Object.entries(entries)) {
    if (!ALLOWED_KEY_SET.has(key)) {
      throw new Error(`Key "${key}" is not allowlisted for wizard writes`);
    }
    if (typeof value !== 'string') {
      throw new TypeError(`Value for "${key}" must be a string`);
    }
    if (value.includes('\n') || value.includes('\r')) {
      throw new Error(`Value for "${key}" must not contain newlines`);
    }
  }
}

/**
 * Merge-writes entries into a dotenv file (default `backup: true`).
 *
 * - Only allowlisted keys are accepted; any other key throws before touching disk.
 * - Unknown keys and comment lines in the existing file are preserved verbatim.
 * - Allowlisted keys already present are upserted in place; absent keys are appended.
 * - If the file does not exist it is created.
 * - Atomic: content is written to a same-directory temp file then renamed over the
 *   target; on failure the temp file is removed and the target is left untouched.
 * - Result is chmod 0600. When `backup` is true and the target exists, a copy is
 *   first made at `<envPath>.bak-<timestamp>`.
 *
 * @param {string} envPath absolute path to the env file
 * @param {Record<string, string>} entries flat key -> value map of allowlisted keys
 * @param {{ backup?: boolean }} [options]
 */
function writeEnv(envPath, entries, { backup = true } = {}) {
  validateEntries(entries);

  if (backup && fs.existsSync(envPath)) {
    fs.copyFileSync(envPath, `${envPath}.bak-${Date.now()}`);
  }

  const existing = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf8') : '';
  const trailingNewline = existing.endsWith('\n');
  const lines = existing === '' ? [] : existing.replace(/\r?\n$/, '').split(/\r?\n/);

  const placed = new Set();
  for (let i = 0; i < lines.length; i += 1) {
    const match = ASSIGNMENT_RE.exec(lines[i]);
    if (match && Object.prototype.hasOwnProperty.call(entries, match[1])) {
      lines[i] = `${match[1]}=${entries[match[1]]}`;
      placed.add(match[1]);
    }
  }

  let appended = false;
  for (const [key, value] of Object.entries(entries)) {
    if (!placed.has(key)) {
      lines.push(`${key}=${value}`);
      appended = true;
    }
  }

  let output = lines.join('\n');
  if (lines.length > 0 && (trailingNewline || appended)) {
    output += '\n';
  }

  const dir = path.dirname(envPath);
  const tempPath = path.join(dir, `.${path.basename(envPath)}.${process.pid}.${Date.now()}.tmp`);
  try {
    fs.writeFileSync(tempPath, output, { mode: 0o600 });
    fs.renameSync(tempPath, envPath);
    fs.chmodSync(envPath, 0o600);
  } catch (err) {
    try {
      if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
    } catch (cleanupErr) {
      // best-effort cleanup; rethrow the original error
    }
    throw err;
  }
}

module.exports = { writeEnv, WIZARD_WRITABLE_KEYS };
