/**
 * Server error and message codes for i18n.
 * Values are i18n keys; client uses t(code, params) to display translated text.
 */

const P = (ns, key) => `${ns}.${key}`;

const SERVER_ERROR_CODES = {
  auth: {
    registrationDisabled: P('serverErrors.auth', 'registrationDisabled'),
    requiredFields: P('serverErrors.auth', 'requiredFields'),
    usernameTaken: P('serverErrors.auth', 'usernameTaken'),
    emailTaken: P('serverErrors.auth', 'emailTaken'),
    emailSendFail: P('serverErrors.auth', 'emailSendFail'),
    registerFail: P('serverErrors.auth', 'registerFail'),
    loginRequiredFields: P('serverErrors.auth', 'loginRequiredFields'),
    loginRateLimit: P('serverErrors.auth', 'loginRateLimit'),
    invalidCredentials: P('serverErrors.auth', 'invalidCredentials'),
    pendingApproval: P('serverErrors.auth', 'pendingApproval'),
    rejected: P('serverErrors.auth', 'rejected'),
    loginFail: P('serverErrors.auth', 'loginFail'),
    refreshTokenInvalid: P('serverErrors.auth', 'refreshTokenInvalid'),
    refreshFail: P('serverErrors.auth', 'refreshFail'),
    userNotFound: P('serverErrors.auth', 'userNotFound'),
    userLoadFail: P('serverErrors.auth', 'userLoadFail'),
  },
  admin: {
    adminRequired: P('serverErrors.admin', 'adminRequired'),
    permissionCheckFail: P('serverErrors.admin', 'permissionCheckFail'),
    settingsLoadFail: P('serverErrors.admin', 'settingsLoadFail'),
    settingsSaveFail: P('serverErrors.admin', 'settingsSaveFail'),
    userListLoadFail: P('serverErrors.admin', 'userListLoadFail'),
    createUserRequiredFields: P('serverErrors.admin', 'createUserRequiredFields'),
    passwordMinLength: P('serverErrors.admin', 'passwordMinLength'),
    usernameTaken: P('serverErrors.admin', 'usernameTaken'),
    emailTaken: P('serverErrors.admin', 'emailTaken'),
    userFolderFail: P('serverErrors.admin', 'userFolderFail'),
    userPermissionFail: P('serverErrors.admin', 'userPermissionFail'),
    createUserFail: P('serverErrors.admin', 'createUserFail'),
    userNotFound: P('serverErrors.admin', 'userNotFound'),
    notPending: P('serverErrors.admin', 'notPending'),
    approveFolderFail: P('serverErrors.admin', 'approveFolderFail'),
    approvePermissionFail: P('serverErrors.admin', 'approvePermissionFail'),
    approveFail: P('serverErrors.admin', 'approveFail'),
    rejectNotFound: P('serverErrors.admin', 'rejectNotFound'),
    notPendingReject: P('serverErrors.admin', 'notPendingReject'),
    rejectFail: P('serverErrors.admin', 'rejectFail'),
    deleteSelf: P('serverErrors.admin', 'deleteSelf'),
    deleteNotFound: P('serverErrors.admin', 'deleteNotFound'),
    deleteOtherAdmin: P('serverErrors.admin', 'deleteOtherAdmin'),
    deleteFail: P('serverErrors.admin', 'deleteFail'),
    folderListFail: P('serverErrors.admin', 'folderListFail'),
    invalidPermissionList: P('serverErrors.admin', 'invalidPermissionList'),
    permissionUpdateFail: P('serverErrors.admin', 'permissionUpdateFail'),
    cleanupFail: P('serverErrors.admin', 'cleanupFail'),
    orphanCleanupFail: P('serverErrors.admin', 'orphanCleanupFail'),
    gcFailed: P('serverErrors.admin', 'gcFailed'),
    repairSyncInvalidAction: P('serverErrors.admin', 'repairSyncInvalidAction'),
    repairSyncNodeNotFound: P('serverErrors.admin', 'repairSyncNodeNotFound'),
    migrationInvalidPayload: P('serverErrors.admin', 'migrationInvalidPayload'),
    migrationMissingRequired: P('serverErrors.admin', 'migrationMissingRequired'),
    migrationAlreadyRunning: P('serverErrors.admin', 'migrationAlreadyRunning'),
    migrationJobNotFound: P('serverErrors.admin', 'migrationJobNotFound'),
  },
  share: {
    shareLinkNotFound: P('serverErrors.share', 'shareLinkNotFound'),
    shareLinkExpired: P('serverErrors.share', 'shareLinkExpired'),
    cannotAddShare: P('serverErrors.share', 'cannotAddShare'),
    fileNotFound: P('serverErrors.share', 'fileNotFound'),
    previewFail: P('serverErrors.share', 'previewFail'),
    downloadFail: P('serverErrors.share', 'downloadFail'),
    pathRequired: P('serverErrors.share', 'pathRequired'),
    invalidExpiration: P('serverErrors.share', 'invalidExpiration'),
  },
  folders: {
    pathRequired: P('serverErrors.folders', 'pathRequired'),
    folderAlreadyExists: P('serverErrors.folders', 'folderAlreadyExists'),
  },
  recentFiles: {
    pathRequired: P('serverErrors.recentFiles', 'pathRequired'),
    movesRequired: P('serverErrors.recentFiles', 'movesRequired'),
    pathsMustBeArrays: P('serverErrors.recentFiles', 'pathsMustBeArrays'),
  },
  files: {
    folderAccessDenied: P('serverErrors.files', 'folderAccessDenied'),
    accessDenied: P('serverErrors.files', 'accessDenied'),
    invalidPath: P('serverErrors.files', 'invalidPath'),
    invalidName: P('serverErrors.files', 'invalidName'),
    notFound: P('serverErrors.files', 'notFound'),
    permissionDenied: P('serverErrors.files', 'permissionDenied'),
    previewNotVideo: P('serverErrors.files', 'previewNotVideo'),
    previewTicketInvalid: P('serverErrors.files', 'previewTicketInvalid'),
    previewTicketExpired: P('serverErrors.files', 'previewTicketExpired'),
    sourceDestRequired: P('serverErrors.files', 'sourceDestRequired'),
    uploadFail: P('serverErrors.files', 'uploadFail'),
    zipFail: P('serverErrors.files', 'zipFail'),
    duplicateFile: P('serverErrors.files', 'duplicateFile'),
    jobNotFound: P('serverErrors.files', 'jobNotFound'),
    progressNotFound: P('serverErrors.files', 'progressNotFound'),
  },
  permissions: {
    permissionHigherThanParent: P('serverErrors.permissions', 'permissionHigherThanParent'),
    viewPermissionsDenied: P('serverErrors.permissions', 'viewPermissionsDenied'),
  },
  permissionRequests: {
    folderOrFileRequired: P('serverErrors.permissionRequests', 'folderOrFileRequired'),
    accessDenied: P('serverErrors.permissionRequests', 'accessDenied'),
    invalidPermission: P('serverErrors.permissionRequests', 'invalidPermission'),
    invalidStatus: P('serverErrors.permissionRequests', 'invalidStatus'),
    userNotFound: P('serverErrors.permissionRequests', 'userNotFound'),
    invalidPathOwner: P('serverErrors.permissionRequests', 'invalidPathOwner'),
    ownerNotFound: P('serverErrors.permissionRequests', 'ownerNotFound'),
    ownPath: P('serverErrors.permissionRequests', 'ownPath'),
    createFail: P('serverErrors.permissionRequests', 'createFail'),
    listInboxFail: P('serverErrors.permissionRequests', 'listInboxFail'),
    listOutboxFail: P('serverErrors.permissionRequests', 'listOutboxFail'),
    pathRequired: P('serverErrors.permissionRequests', 'pathRequired'),
    invalidRequestId: P('serverErrors.permissionRequests', 'invalidRequestId'),
    requestNotFound: P('serverErrors.permissionRequests', 'requestNotFound'),
    onlyPendingApprove: P('serverErrors.permissionRequests', 'onlyPendingApprove'),
    approveFail: P('serverErrors.permissionRequests', 'approveFail'),
    checkOwnerFail: P('serverErrors.permissionRequests', 'checkOwnerFail'),
  },
  requireUser: {
    authenticationRequired: P('serverErrors.requireUser', 'authenticationRequired'),
  },
  permissionsMiddleware: {
    pathRequired: P('serverErrors.permissionsMiddleware', 'pathRequired'),
    authenticationRequired: P('serverErrors.permissionsMiddleware', 'authenticationRequired'),
    accessDenied: P('serverErrors.permissionsMiddleware', 'accessDenied'),
    checkFail: P('serverErrors.permissionsMiddleware', 'checkFail'),
  },
  errorHandler: {
    defaultMessage: P('serverErrors.errorHandler', 'defaultMessage'),
    internalServerError: P('serverErrors.errorHandler', 'internalServerError'),
    databaseConflict: P('serverErrors.errorHandler', 'databaseConflict'),
    databaseConstraintViolation: P('serverErrors.errorHandler', 'databaseConstraintViolation'),
    databaseUnavailable: P('serverErrors.errorHandler', 'databaseUnavailable'),
    databaseQueryFailed: P('serverErrors.errorHandler', 'databaseQueryFailed'),
  },
  api: {
    webdavTestFailed: P('serverErrors.api', 'webdavTestFailed'),
  },
  thumbnails: {
    invalidOrExpiredToken: P('serverErrors.thumbnails', 'invalidOrExpiredToken'),
    notFound: P('serverErrors.thumbnails', 'notFound'),
  },
  webdav: {
    credentialsNotConfigured: P('serverErrors.webdav', 'credentialsNotConfigured'),
    serverNotResponding: P('serverErrors.webdav', 'serverNotResponding'),
    cannotConnect: P('serverErrors.webdav', 'cannotConnect'),
    allConnectionAttemptsFailed: P('serverErrors.webdav', 'allConnectionAttemptsFailed'),
    operationFailed: P('serverErrors.webdav', 'operationFailed'),
    pathNotFound: P('serverErrors.webdav', 'pathNotFound'),
    permissionDeniedUpload: P('serverErrors.webdav', 'permissionDeniedUpload'),
    conflictUpload: P('serverErrors.webdav', 'conflictUpload'),
    connectionRefused: P('serverErrors.webdav', 'connectionRefused'),
    uploadFailed: P('serverErrors.webdav', 'uploadFailed'),
    fileOrFolderNotFound: P('serverErrors.webdav', 'fileOrFolderNotFound'),
    permissionDeniedDelete: P('serverErrors.webdav', 'permissionDeniedDelete'),
    dirNotEmptyOrConflict: P('serverErrors.webdav', 'dirNotEmptyOrConflict'),
    deleteFailed: P('serverErrors.webdav', 'deleteFailed'),
    destinationExists: P('serverErrors.webdav', 'destinationExists'),
    sourceNotFound: P('serverErrors.webdav', 'sourceNotFound'),
    createDirFailed: P('serverErrors.webdav', 'createDirFailed'),
  },
  thumbnail: {
    downloadFailed: P('serverErrors.thumbnail', 'downloadFailed'),
    videoDownloadFailed: P('serverErrors.thumbnail', 'videoDownloadFailed'),
    frameExtractionFailed: P('serverErrors.thumbnail', 'frameExtractionFailed'),
    ffmpegFailed: P('serverErrors.thumbnail', 'ffmpegFailed'),
  },
  selectiveTransfer: {
    invalidMode: P('serverErrors.selectiveTransfer', 'invalidMode'),
    callbacksRequired: P('serverErrors.selectiveTransfer', 'callbacksRequired'),
    accessDenied: P('serverErrors.selectiveTransfer', 'accessDenied'),
    destinationExists: P('serverErrors.selectiveTransfer', 'destinationExists'),
  },
  storage: {
    invalidPathMapping: P('serverErrors.storage', 'invalidPathMapping'),
    postgresqlNotConfigured: P('serverErrors.storage', 'postgresqlNotConfigured'),
  },
  users: {
    emailRequired: P('serverErrors.users', 'emailRequired'),
  },
  utilsAuth: {
    accessTokenRequired: P('serverErrors.utilsAuth', 'accessTokenRequired'),
    invalidOrExpiredToken: P('serverErrors.utilsAuth', 'invalidOrExpiredToken'),
    shareLinkNotFound: P('serverErrors.utilsAuth', 'shareLinkNotFound'),
    shareLinkExpired: P('serverErrors.utilsAuth', 'shareLinkExpired'),
    tokenRequired: P('serverErrors.utilsAuth', 'tokenRequired'),
  },
};

const SERVER_MESSAGE_CODES = {
  auth: {
    registerSuccess: P('serverMessages.auth', 'registerSuccess'),
    loginSuccess: P('serverMessages.auth', 'loginSuccess'),
  },
  admin: {
    settingsSaved: P('serverMessages.admin', 'settingsSaved'),
    userAdded: P('serverMessages.admin', 'userAdded'),
    userApproved: P('serverMessages.admin', 'userApproved'),
    userRejected: P('serverMessages.admin', 'userRejected'),
    userDeleted: P('serverMessages.admin', 'userDeleted'),
    permissionUpdated: P('serverMessages.admin', 'permissionUpdated'),
    orphanCleanupDone: P('serverMessages.admin', 'orphanCleanupDone'),
    gcDone: P('serverMessages.admin', 'gcDone'),
    repairSyncDone: P('serverMessages.admin', 'repairSyncDone'),
    migrationCancelled: P('serverMessages.admin', 'migrationCancelled'),
  },
  folders: {
    createSuccess: P('serverMessages.folders', 'createSuccess'),
  },
  recentFiles: {
    clearedSuccess: P('serverMessages.recentFiles', 'clearedSuccess'),
  },
  api: {
    healthOk: P('serverMessages.api', 'healthOk'),
    webdavTestOk: P('serverMessages.api', 'webdavTestOk'),
  },
  share: {
    addedToShared: P('serverMessages.share', 'addedToShared'),
  },
  shareLinks: {
    shareLinkDeleted: P('serverMessages.shareLinks', 'shareLinkDeleted'),
  },
  files: {
    copySuccess: P('serverMessages.files', 'copySuccess'),
    deleteSuccess: P('serverMessages.files', 'deleteSuccess'),
    moveSuccess: P('serverMessages.files', 'moveSuccess'),
    nameUnchanged: P('serverMessages.files', 'nameUnchanged'),
    renameSuccess: P('serverMessages.files', 'renameSuccess'),
    uploadSkipped: P('serverMessages.files', 'uploadSkipped'),
    uploadSuccess: P('serverMessages.files', 'uploadSuccess'),
    cancelRequested: P('serverMessages.files', 'cancelRequested'),
  },
  permissions: {
    permissionGranted: P('serverMessages.permissions', 'permissionGranted'),
    permissionRevoked: P('serverMessages.permissions', 'permissionRevoked'),
    filePermissionGranted: P('serverMessages.permissions', 'filePermissionGranted'),
    filePermissionRevoked: P('serverMessages.permissions', 'filePermissionRevoked'),
    filePermissionUpdated: P('serverMessages.permissions', 'filePermissionUpdated'),
  },
  users: {
    passwordUpdated: P('serverMessages.users', 'passwordUpdated'),
    emailUpdated: P('serverMessages.users', 'emailUpdated'),
    permissionUpdated: P('serverMessages.users', 'permissionUpdated'),
  },
};

module.exports = {
  SERVER_ERROR_CODES,
  SERVER_MESSAGE_CODES,
};
